os:
  - linux
  - osx

language: c

python:
  - "2.7"

script:
  - make
  - echo '0123456789' > test-file
  - export WEIGHT=$(python -c 'print "{0:.6e}".format(9.2732796E-20 * 31750000 * 11 / 1000 * 8)')
  - export EXPECTED="The file test-file weighs about $WEIGHT grams."
  - export OUTPUT=$(./fileweight test-file)
  - '[ "$EXPECTED" == "$OUTPUT" ]'

after_success:
  - make clean
